---
# ========================================
# Browsers and Testing Tools Installation
# ========================================

- name: Install Firefox
  shell: "{{ installer_script_folder }}/install-firefox.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install Microsoft Edge
  shell: "{{ installer_script_folder }}/install-microsoft-edge.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install Google Chrome
  shell: "{{ installer_script_folder }}/install-google-chrome.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install Selenium
  shell: "{{ installer_script_folder }}/install-selenium.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}" 