---
# ========================================
# Compilers Installation
# ========================================

- name: Install Clang
  shell: "{{ installer_script_folder }}/install-clang.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install Swift
  shell: "{{ installer_script_folder }}/install-swift.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install GCC Compilers
  shell: "{{ installer_script_folder }}/install-gcc-compilers.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install GFortran
  shell: "{{ installer_script_folder }}/install-gfortran.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}" 