---
# ========================================
# Development Tools Installation
# ========================================

- name: Install CMake
  shell: "{{ installer_script_folder }}/install-cmake.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install CodeQL Bundle
  shell: "{{ installer_script_folder }}/install-codeql-bundle.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install Ninja
  shell: "{{ installer_script_folder }}/install-ninja.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install Bazel
  shell: "{{ installer_script_folder }}/install-bazel.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"

- name: Install VCPKG
  shell: "{{ installer_script_folder }}/install-vcpkg.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}" 