---
# ========================================
# Specialized Tools Installation
# ========================================

- name: Install ORAS CLI
  shell: "{{ installer_script_folder }}/install-oras-cli.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"

- name: Install Android SDK
  shell: "{{ installer_script_folder }}/install-android-sdk.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}" 