---
# ========================================
# Version Control Tools Installation
# ========================================

- name: Install Git
  shell: "{{ installer_script_folder }}/install-git.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install Git LFS
  shell: "{{ installer_script_folder }}/install-git-lfs.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}"

- name: Install GitHub CLI
  shell: "{{ installer_script_folder }}/install-github-cli.sh"
  environment:
    HELPER_SCRIPTS: "{{ helper_script_folder }}"
    INSTALLER_SCRIPT_FOLDER: "{{ installer_script_folder }}"
    DEBIAN_FRONTEND: "{{ debian_frontend }}" 